name: core16-extras
version: 16-2
version-script: |
    # remember to keep version script in sync with "Makefile"
    echo "16-$(date +%Y%m%d)"
summary: core16 runtime environment
description: The core16 runtime environment
confinement: strict
type: base
grade: stable

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure


  packages:
    after: [hooks, livebuild]
    plugin: nil
    override-build: |
      snapcraftctl build
      # setup necessary empty folders for snapd to bind mount on top of
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/snap
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/snapd
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/lib/snapd
      mkdir -p $SNAPCRAFT_PART_INSTALL/snap

      # setup symlink for snapctl so that snaps and hooks can call it
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s ../lib/snapd/snapctl snapctl
    stage-packages:
      - python2.7
      - nodejs
      - sqlite3
      - wget
      - rsync
      - openjdk-8-jdk

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
      - shellcheck
      - gawk
